# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "spud_media"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.date = "2012-01-28"
  s.files = [
    "app/assets/images/spud/admin/files_thumbs/dat_thumb.png",
    "app/assets/images/spud/admin/files_thumbs/doc_thumb.png",
    "app/assets/images/spud/admin/files_thumbs/jpg_thumb.png",
    "app/assets/images/spud/admin/files_thumbs/mp3_thumb.png",
    "app/assets/images/spud/admin/files_thumbs/pdf_thumb.png",
    "app/assets/images/spud/admin/files_thumbs/png_thumb.png",
    "app/assets/images/spud/admin/files_thumbs/ppt_thumb.png",
    "app/assets/images/spud/admin/files_thumbs/txt_thumb.png",
    "app/assets/images/spud/admin/files_thumbs/xls_thumb.png",
    "app/assets/images/spud/admin/files_thumbs/zip_thumb.png",
    "app/assets/images/spud/admin/media_thumb.png",
    "app/controllers/spud/admin/media_controller.rb",
    "app/helpers/spud/admin/users_helper.rb",
    "app/helpers/spud/user_sessions_helper.rb",
    "app/models/spud_media.rb",
    "app/views/spud/admin/media/index.html.erb",
    "app/views/spud/admin/media/new.html.erb",
    "config/application.rb",
    "config/boot.rb",
    "config/routes.rb",
    "lib/spud_media.rb",
    "lib/spud_media/configuration.rb",
    "lib/spud_media/engine.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Spud Media File Upload/Storage Engine"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<spud_admin>, [">= 0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
    else
      s.add_dependency(%q<spud_admin>, [">= 0"])
      s.add_dependency(%q<paperclip>, [">= 0"])
    end
  else
    s.add_dependency(%q<spud_admin>, [">= 0"])
    s.add_dependency(%q<paperclip>, [">= 0"])
  end
end

